# Create User
POST http://localhost:5000/users
Content-Type: application/json


{
    "name": "Siswa 2",
    "password": "1234",
    "confPassword": "123",
    "role": "user",
    "nis":"12345"
}
###
# Get all user
GET http://localhost:5000/users


###
# GET SINGLE USER
GET http://localhost:5000/users/97340949-2eee-43fe-836e-3f142f17875f


###
# Login request
POST http://localhost:5000/login
Content-Type: application/json

{
    "nis": "123",
    "password": "123"
}

###
# Update
PATCH  http://localhost:5000/users/00cc4abd-25a7-49f2-ad23-e5fe488bdd7e
Content-Type: application/json


{
    "name": "Siswa",
    "nis": "1234",
    "password": "123",

    "confPassword": "123",
    "role": "user"
}


###
# Delate
DELETE http://localhost:5000/users/2a60f550-bf95-4453-8ab9-455e57c78361



### 
# Login USer

POST http://localhost:3000/login
Content-Type: application/json

{
    "nis": "123",
    "password": "123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Faldi@gmail.com",
    "password": "123456"
}


###
GET http://localhost:5000/me
Content-Type: application/json

###
DELETE http://localhost:5000/logout


###
# Get All product
GET http://localhost:5000/products


###
# Get single product
GET http://localhost:5000/products/b9b966c6-816c-468a-89c5-a1d1f423863d

###
# Menambahkan data produk
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Kelas 6",
    "price": 34
}


###
# Update Product
PATCH http://localhost:5000/products/b9b966c6-816c-468a-89c5-a1d1f423863d
Content-Type: application/json

{
    "name": "Kelas Update",
    "price": 341
}


###
# Delete Product

DELETE http://localhost:5000/products/975fa411-18cf-46f4-90c9-a943f1c96bfa



###
# Dafatr Guru
POST http://localhost:5000/register-guru
Content-Type: application/json

{
  "fullName": "John Doe",
  "nip": "123456789",
  "password": "password123",
  "school": "SMA 1 Jakarta"
}
####
#Daftar Siswa
POST http://localhost:5000/register-siswa
Content-Type: application/json

{
  "fullName": "SISWA",
  "nis": "1234",
  "password": "123",
  "class": "10A",
  "token": "123"
}

###
# Update Progress
PATCH http://localhost:5000/users/96a50fbb-f93a-48c3-9194-4943d9d3a9f4/progress
Content-Type: application/json

{
  "progress": 0
}


####
# Latihan 1

POST http://localhost:5000/scores
Content-Type: application/json
Cookie: connect.sid=<your_session_cookie>

{
  "user_id": "8e95e7e8-7345-4db6-98b3-e5f4c27c7395",
  "type": "latihan",
  "chapter": 1,
  "score": 85
}
