# Create User
POST http://localhost:5000/users
Content-Type: application/json


{
    "name": "Chim",
    "email": "chim@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}


###
# Get all user
GET http://localhost:5000/users


###
# GET SINGLE USER
GET http://localhost:5000/users/97340949-2eee-43fe-836e-3f142f17875f

###
# Update
PATCH  http://localhost:5000/users/97340949-2eee-43fe-836e-3f142f17875f
Content-Type: application/json


{
    "name": "FALDI UPDATE",
    "email": "admin@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}


###
# Delate
DELETE http://localhost:5000/users/2a60f550-bf95-4453-8ab9-455e57c78361



### 
# Login USer

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "chim@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}


###
GET http://localhost:5000/me
Content-Type: application/json

###
DELETE http://localhost:5000/logout


###
# Get All product
GET http://localhost:5000/products


###
# Get single product
GET http://localhost:5000/products/b9b966c6-816c-468a-89c5-a1d1f423863d

###
# Menambahkan data produk
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Kelas 6",
    "price": 34
}


###
# Update Product
PATCH http://localhost:5000/products/b9b966c6-816c-468a-89c5-a1d1f423863d
Content-Type: application/json

{
    "name": "Kelas Update",
    "price": 341
}


###
# Delete Product

DELETE http://localhost:5000/products/975fa411-18cf-46f4-90c9-a943f1c96bfa